### PR TITLE
July release of Cosmic-OS for oneplus2

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: anupritaisno1 <www.anuprita804@gmail.com>

### CODE REVIEW

**Comment by sagarshah1729** [comment]
@anupritaisno1 No u. Please upload on sourceforge

**Comment by shivamdev-lgtm** [comment]
@anupritaisno1 Lolol

**Comment by Sid-Sun** [comment]
@anupritaisno1 What kind of sorcery is this? A pull request?

**Comment by ghost** [comment]
@sagarshah1729 No no u

**Pull request merged**
