### PR TITLE
[DO NOT MERGE] Update for plausible future gdrive hosting.

### PR DESCRIPTION
**Pull request by Sid-Sun**
Thanks to @Adesh15 for the fileid part

Signed-off-by: Sid-Sun <sid-sun@outlook.com>

### CODE REVIEW

**Comment by Sid-Sun** [comment]
@Sid-Sun Ssh it's a secret

**Comment by Sid-Sun** [comment]
I knew I'd want to see some part of script later and today's the day :P

**Comment by Abhinavgupta371** [comment]
@Sid-Sun high?

**Comment by shivamdev-lgtm** [comment]
@Sid-Sun Eh?

**Pull request closed without merging**
