### PR TITLE
oneplus2: fix maintainer name

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: anupritaisno1 <www.anuprita804@gmail.com>

### CODE REVIEW

**Comment by Sid-Sun** [comment]
@anupritaisno1 Wot about this

**Comment by ghost** [comment]
@Sid-Sun @SidSun

**Comment by ghost** [comment]
@anupritaisno1 Merge it

**Comment by ghost** [comment]
@anupritaisno1 Aaaaaaaaa

**Review by Sid-Sun — APPROVED** [review]
Joker Approves this.

**Pull request merged**
