### PR TITLE
OTA: Update falcon (10/08/2018)

### PR DESCRIPTION
**Pull request by Klozz**

### CODE REVIEW

**Comment by ghost** [comment]
@Klozz Invalid sha256
Use sha256sum *zip

**Comment by ghost** [comment]
@anupritaisno1 "fix official on my pc"
Ambiguous commit in changelog, please be clear about what you're doing

**Comment by ghost** [comment]
@anupritaisno1 Wait a second identify yourself
I can't see your device repo on https://github.com/Cosmic-Devices?tab=repositories

**Comment by ghost** [comment]
@anupritaisno1 Refusing to merge
Reasons:
Person who created this PR doesn't have a repo yet on the official device repo

Your XDA thread does not link to a proper kernel source, as a ROM team we don't want legal trouble with XDA and you should correct the kernel source link first
https://forum.xda-developers.com/moto-g/development/falcon-cosmic-os-3-1-t3730942

**Comment by ghost** [comment]
@anupritaisno1 Also I can't see any kernel changes in your changelog. While this will not affect the merge do remember that your security patch date is not real if you continue with this

**Comment by Klozz** [comment]
LUL since the start i dont have device tree on COSMIC-DEVICES none of my supported arent in cosmic-devices.
the change of vendor is not ambiguos I dont want to set custom name for HOST
I worked as is since the start, the next time please write all your message in 1 message dont spam

**Comment by ghost** [comment]
@Klozz Now that you've argued with me you'll update all your threads and link to the proper kernel source and device tree otherwise you'll be reported to XDA

You have got 2 minutes

**Comment by ghost** [comment]
@anupritaisno1 @Klozz if I don't see a kernel source on all of your cosmic threads in the next 2 minutes I will resort to stricter measures

**Comment by ghost** [comment]
@anupritaisno1 First off you're breaking the law by not uploading the kernel source

Second of all this is an official repo. You must provide the device tree

@Klozz

**Comment by Klozz** [comment]
forget i leave this the source is published, Sagar or anyone else never forced me to upload my device tree because they know where is located, but I really do not feel like arguing with someone like you, who arrives in an aggressive way.
Good day.

**Comment by ghost** [comment]
@Klozz Kernel source?

**Comment by ghost** [comment]
@Klozz Or do you want a moderator on XDA to send you an angry message?

**Comment by Klozz** [comment]
Do what you want , seems you dont know how to search in xda.

**Comment by ghost** [comment]
@Klozz I'm not searching on XDA and assuming
Fix your kernel source link

**Comment by ghost** [comment]
@Klozz If XDA catches you
We lose official status for 4+ devices
you'll be banned
All of your work will also be banned
And we'll definitely not have a good maintainer like you

You want that to happen? I guess not

**Comment by sagarshah1729** [comment]
@anupritaisno1 Stop with it! You don't need to be rude!

**Comment by sagarshah1729** [comment]
@Klozz Please do the PR again. I will merge it 🙄

**Pull request closed without merging**
